server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/databaseone
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

mybatis:
  type-aliases-package: com.dtb.springdatabase
  mapper-locations:
  - classpath:mybatis/*.xml
  